# Generated by Django 4.1 on 2023-11-12 10:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="usertype",
            field=models.CharField(default="employee", max_length=255),
        ),
    ]
